apiVersion: v1
kind: Service
metadata:
  name: fitnessapp
  labels:
    app: fitnessapp
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: fitnessapp
  type: LoadBalancer
  externalIPs: ["18.232.111.45"]
  

